services:
  # --- SERVEI DE BASE DE DADES (MySQL) ---
  mysql-db:
    image: mysql:latest
    container_name: mysql-compose-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin      # <--- ¡ESTA LÍNEA ES LA QUE TE FALTABA!
      MYSQL_DATABASE: fruit_db_n2
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # --- SERVEI DE BASE DE DADES (MongoDB) ---
  mongodb:
    image: mongo:latest
    container_name: mongo-db-fruit
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # --- SERVEI DE L'APLICACIÓ (Spring Boot) ---
  fruit-api:
    build: .
    container_name: fruit-api-compose
    ports:
      - "8080:8080"
    environment:
      # Config MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-compose-db:3306/fruit_db_n2?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Config MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db-fruit:27017/fruit_orders_db
    depends_on:
      - mysql-db
      - mongodb
    restart: on-failure

volumes:
  mysql_data:
  mongo_data: